development:
  adapter: postgresql
  encoding: unicode
  database: popeye_development
  pool: 5
  username: michaelverdi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: popeye_test
  pool: 5
  username: michaelverdi
  password:
